name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - bhagavdgita
body:
  - type: markdown
    attributes:
      value: |
        Thank you to filling out this bug report. This is where you can report issues so we can fix them. Please fill up all required fields 
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? (optional)
      placeholder: email@example.com
    validations:
      required: false
  - type: textarea
    id: what-expect
    attributes:
      label: What did you expect?
      description: What did you expect to happen when you did whatever you did?
      placeholder: I expected it to ...
    validations:
      required: true
  - type: textarea
    id: what-happend
    attributes:
      label: What actually happend?
      description: What was the thing that happened unexpectedly?
      placeholder: ... happened instead
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0 (pre-release)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      multiple: true
      options:
        - Android 5
        - iOS (iPhone)
  - type: dropdown
    id: os-version
    attributes:
      label: What iOS or Android version are you using?
      multiple: true
      options:
        - iOS 7 and below
        - iOS 8
        - iOS 9
        - iOS 10
        - iOS 11
        - iOS 12
        - iOS 13
        - iOS 14
        - iOS 15
        - iOS 16 (beta)
        - Android Ice Cream Sandwich and below
        - Android Lollipop
        - Android Marshmallow
        - Android Nougat
        - Android Oreo
        - Android Pie
        - Android 10 (Android Q)
        - Android 11 (Red Velvet Cake)
        - Android 12 (Snow Cone)
        - Android 13 (Tiramisu)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/bhagavdgita/bhagavdgita.github.io/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
