# Gita App
platform :ios, '16.0'

target 'Gita' do
  pod 'GoogleMLKit/Translate', '3.2.0'
  pod 'Auth0', '~> 2.4'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
  end
 end
end
